"""empty message

Revision ID: 468e0d4a2a35
Revises: 4161a440f5bf
Create Date: 2022-04-15 21:10:33.266048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '468e0d4a2a35'
down_revision = '4161a440f5bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=30), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
