"""empty message

Revision ID: 502d68a4745d
Revises: 468e0d4a2a35
Create Date: 2022-04-21 21:41:30.764753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502d68a4745d'
down_revision = '468e0d4a2a35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('person_no', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'car', 'person', ['person_no'], ['no'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car', type_='foreignkey')
    op.drop_column('car', 'person_no')
    # ### end Alembic commands ###
